name: Publicar noticias en WordPress

on:
  schedule:
    - cron: "0 11 * * *"  # Se ejecuta todos los días a las 11:00 UTC (6:00 AM hora de Bogotá)
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions  

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade python-wordpress-xmlrpc
          pip install pytz

      - name: Crear archivo de log vacío (si no existe)
        run: |
          touch proceso_noticias.log

      - name: Ejecutar script de publicacion
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          python cats_automatics_news.py || { echo "Error en el script de publicación." >> proceso_noticias.log; exit 1; }

      - name: Guardar logs como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: logs-publicacion
          path: proceso_noticias.log
          retention-days: 7